# Generated by Django 2.0.4 on 2018-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
